version: '3.1'

services:

  mongodb:
    image: mongo:6.0.8
    restart: always
    container_name: hyper-mongo
    ports:
      - '27027:27017'
    env_file: ['.env']
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - hyper-task-manager-network

  hyper-service:
    build: .
    container_name: hyper-task-manager
    depends_on:
      - mongodb
    ports:
      - '8000:8000'
    env_file: ['.env']
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    networks:
      - hyper-task-manager-network

volumes:
  mongo-data:

networks:
  hyper-task-manager-network:
